language: scala
scala:
    - 2.13.3

os:
  - linux

jdk:
  - oraclejdk11

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - sbt +test
  - sbt +publishLocal
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - $HOME/.ivy2/cache

before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/br.com.felipebonezi
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/br.com.felipebonezi
  - rm -rf $HOME/.ivy2/cache/com.github.felipebonezi
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.github.felipebonezi

  # Delete all ivy data files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
